### ISSUE TITLE
autotest_remote_unittest regression

### ISSUE THREAD

**Issue by vinsonlee** [autotest/autotest#429]
# 
## ERROR: test_autoserv_install (**main**.TestBaseAutotest)

Traceback (most recent call last):
  File "./server/autotest_remote_unittest.py", line 145, in test_autoserv_install
    self.base_autotest.install()
  File "autotest/server/autotest_remote.py", line 132, in install
    self._install(host=host, autodir=autodir)
  File "autotest/server/autotest_remote.py", line 254, in _install
    self._create_test_output_dir(host, autodir)
  File "autotest/server/autotest_remote.py", line 119, in _create_test_output_dir
    default=tmpdir)
  File "autotest/client/shared/test_utils/mock.py", line 209, in __call__
    return self.playback(self.symbol, _args, *_dargs)
  File "autotest/client/shared/test_utils/mock.py", line 492, in __method_playback
    self._append_error(msg)
  File "autotest/client/shared/test_utils/mock.py", line 504, in _append_error
    raise CheckPlaybackError(error)
CheckPlaybackError: unexpected call: get_config_value('COMMON', 'test_output_dir', default='autodir/tmp')
# 
## ERROR: test_full_client_install (**main**.TestBaseAutotest)

Traceback (most recent call last):
  File "./server/autotest_remote_unittest.py", line 128, in test_full_client_install
    self.base_autotest.install_full_client()
  File "autotest/server/autotest_remote.py", line 137, in install_full_client
    use_packaging=False)
  File "autotest/server/autotest_remote.py", line 254, in _install
    self._create_test_output_dir(host, autodir)
  File "autotest/server/autotest_remote.py", line 119, in _create_test_output_dir
    default=tmpdir)

  File "autotest/client/shared/test_utils/mock.py", line 209, in **call**
    return self.playback(self.symbol, _args, *_dargs)
  File "autotest/client/shared/test_utils/mock.py", line 492, in __method_playback
    self._append_error(msg)
  File "autotest/client/shared/test_utils/mock.py", line 504, in _append_error
    raise CheckPlaybackError(error)
CheckPlaybackError: unexpected call: get_config_value('COMMON', 'test_output_dir', default='autodir/tmp')
# 
## ERROR: test_packaging_install (**main**.TestBaseAutotest)

Traceback (most recent call last):
  File "./server/autotest_remote_unittest.py", line 166, in test_packaging_install
    self.base_autotest.install()
  File "autotest/server/autotest_remote.py", line 132, in install
    self._install(host=host, autodir=autodir)
  File "autotest/server/autotest_remote.py", line 234, in _install
    self._install_using_packaging(host, autodir)
  File "autotest/server/autotest_remote.py", line 163, in _install_using_packaging
    self._create_test_output_dir(host, autodir)
  File "autotest/server/autotest_remote.py", line 119, in _create_test_output_dir
    default=tmpdir)
  File "autotest/client/shared/test_utils/mock.py", line 209, in __call__
    return self.playback(self.symbol, _args, *_dargs)
  File "autotest/client/shared/test_utils/mock.py", line 492, in __method_playback
    self._append_error(msg)
  File "autotest/client/shared/test_utils/mock.py", line 504, in _append_error
    raise CheckPlaybackError(error)
CheckPlaybackError: unexpected call: get_config_value('COMMON', 'test_output_dir', default='autodir/tmp')
# 
## ERROR: test_run (**main**.TestBaseAutotest)

Traceback (most recent call last):
  File "./server/autotest_remote_unittest.py", line 238, in test_run
    self.base_autotest.run(control, timeout=30)
  File "autotest/server/autotest_remote.py", line 336, in run
    client_disconnect_timeout)
  File "autotest/server/autotest_remote.py", line 365, in _do_run
    atrun.remote_control_state,
AttributeError: 'cls_sub' object has no attribute 'remote_control_state'

FAILED (errors=4)

2648c15700a1af63f94775a852f6b19266ec5836 is the first bad commit
commit 2648c15700a1af63f94775a852f6b19266ec5836
Author: Lucas Meneghel Rodrigues lmr@redhat.com
Date:   Tue Jun 26 20:29:30 2012 -0300

```
server.autotest_remote: Transfer and clean state files properly

The autotest_remote code assumes the state of remote
control files is simply path/to/control + ".state". This
causes problem with our patches moving state file creation
to the test output dir set on global_config.ini, with
fall back to the autotest tmpdir area.

Fix the code, creating new attributes for the _BaseRun
class, that will make it easier to control and keep
consistency of the state file locations.

Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>
```

:040000 040000 c13b9af36ffe048b590a12792fb1082786c4f42a 432058405ede6cfe2d76d211f273adbcf33bef7a M  server
bisect run success
