### ISSUE TITLE
rpm_kernel_unittest regression

### ISSUE THREAD

**Issue by vinsonlee** [autotest/autotest#282]
$ ./server/rpm_kernel_unittest.py 
# ....E
## ERROR: test_install (**main**.TestRpmKernel)

Traceback (most recent call last):
  File "./server/rpm_kernel_unittest.py", line 51, in test_install
    host.bootloader.remove_kernel.expect_call('autotest')
AttributeError: 'mock_class' object has no attribute 'remove_kernel'

---

Ran 5 tests in 0.002s

FAILED (errors=1)

2d3a8d602dd239a22daf05f1124c0f21b4ed6548 is the first bad commit
commit 2d3a8d602dd239a22daf05f1124c0f21b4ed6548
Author: Lucas Meneghel Rodrigues lmr@redhat.com
Date:   Tue Apr 10 21:41:33 2012 -0300

```
boottool: auto install of grubby for users of the client library

The boottool CLI already does auto installation of grubby if a
recent enough version is not found on the system. This patch
makes that feature a function that can also be used by users of
the boottool client library, at instantiation time.

Signed-off-by: Cleber Rosa <crosa@redhat.com>
```
