### ISSUE TITLE
deb_kernel_unittest regression

### ISSUE THREAD

**Issue by vinsonlee** [autotest/autotest#281]
$ ./server/deb_kernel_unittest.py 
# .E
## ERROR: test_install (**main**.TestDebKernel)

Traceback (most recent call last):
  File "./server/deb_kernel_unittest.py", line 57, in test_install
    self.host.bootloader.add_kernel.expect_call('/boot/vmlinuz-1',
AttributeError: 'mock_class' object has no attribute 'add_kernel'

---

Ran 2 tests in 0.001s

FAILED (errors=1)

67d53d06dfc6ab7ee24bcf7ccd530050d9e1bb2c is the first bad commit
commit 67d53d06dfc6ab7ee24bcf7ccd530050d9e1bb2c
Author: Cleber Rosa crosa@redhat.com
Date:   Mon Mar 5 00:06:41 2012 -0300

```
boottool: adapt server side bootloader.py for rewrite of bootool

Signed-off-by: Cleber Rosa <crosa@redhat.com>
```
